### ISSUE TITLE
Рекомендация

### ISSUE THREAD

**Issue by Muxamedin** [YokaEnenra/HillelPython#3]
https://github.com/YokaEnenra/HillelPython/blob/18ad4bf8a06d37fb8da4033afbee9ce633efca44/Lesson6_HomeWork/Task_NumberPyramid/pyramid.py#L9

Вот еще один способ как можно проверить в python  на то что число в диапазоне 

if number in range(1,101):
   ....

**Comment by YokaEnenra** [comment]
Понял, поменял проверку на эту, спасибо за подсказку
