### ISSUE TITLE
Не соответствует требованиям задачи -  нету второго тестового примера 

### ISSUE THREAD

**Issue by Muxamedin** [YokaEnenra/HillelPython#4]
Написать функцию которая принимает на вход параметры : список чисел любой
   дины и число .
   Функция должна проверить есть ли в списке 2 числа сума которых
   еквивалентна числу переданому 2м параметром. Функция должна вернуть
   булевое значение - результат поиска фукции.
   
   Для проверки вызвать 2 раза функцию с разными тестовыми примерами.
   
   
https://github.com/YokaEnenra/HillelPython/blob/b36ee52b5da863a728543a17cf39d7ab60e2ab52/Lesson9_HomeWork/Task_IfSumInNumber/if_summ.py#L10

**Comment by YokaEnenra** [comment]
Исправлено
