### ISSUE TITLE
Хардкод числа учеников 

### ISSUE THREAD

**Issue by Muxamedin** [YokaEnenra/HillelPython#5]
https://github.com/YokaEnenra/HillelPython/blob/96f2109097231d5934eea2a0e7b29fc4ab9dd494/Lesson14_HomeWork/Task_Pupils/pupils.py#L24

Этот код зависит от файла который он читает так как ожидается что 12 оценок всегда в файле 
А что если тестовый файл поменяется  и будет больше или меньше  оценок ? правильно ли тогда будет работать ? 
Может есть другой способ получить число для выполнения подсчета средней оценки ?

**Comment by YokaEnenra** [comment]
Исправлено
